### ISSUE TITLE
Issue when querying with a client created with App Token

### ISSUE THREAD

**Issue by RealWorldDevelopers** [CityofSantaMonica/SODA.NET#81]
When creating a client via these overloads:
```
 var sodaHost = "https://data.ny.gov";
 var soda4x4 = "5xaw-6ayf";

var client = new SodaClient(sodaHost, sodaAppToken);
var client = new SodaClient(sodaHost, sodaAppToken, user, pwd);  
var client = new SodaClient(sodaHost, sodaAppToken, keyId, keySecret); 
```
Any GetRows or GetResource Method will return this error:
```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=The provided resourceId is not a valid Socrata (4x4) resource identifier.
Parameter name: resourceId
  Source=SODA
  StackTrace:
   at SODA.SodaClient.Query[TRow](SoqlQuery soqlQuery, String resourceId)
   at SODA.Resource`1.Query[T](SoqlQuery soqlQuery)
   at SODA.Resource`1.Query(SoqlQuery soqlQuery)
   at NumPicker.Controllers.HomeController.MegaMillions() in C:\Users\ka8kgj\Desktop\NumPicker\NumPicker\Controllers\HomeController.cs:line 43
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
```

However, using the anonymous client works fine.
`var client = new SodaClient(sodaHost);`

**Comment by thekaveman** [comment]
Hi @RealWorldDevelopers, thanks for the report.

Without knowing more details of your code, and based on the StackTrace, it looks like the `soda4x4` parameter may be passed incorrectly to the `SODA.SodaClient.Query[TRow](SoqlQuery soqlQuery, String resourceId)` method.

Would you mind pasting a few more lines where `soda4x4` is used in your code? I was able to get rows back using all 3 of the overloads for `SodaClient` you mention.

**Comment by thekaveman** [comment]
For reference, here is the code I wrote that works:

```csharp
var sodaHost = "https://data.smgov.net";
var soda4x4 = "w8ue-6cnd";
var sodaAppToken = "app-token";

var clientTokenOnly = new SodaClient(sodaHost, sodaAppToken);
var tokenResource = clientTokenOnly.GetResource<dynamic>(soda4x4);
var tokenRows = tokenResource.GetRows(10);
Console.WriteLine("Got {0} rows using token only", tokenRows.Count());

var user = "username";
var pwd = "password";
var clientTokenUserPass = new SodaClient(sodaHost, sodaAppToken, user, pwd);
var tokenUserPassResource = clientTokenUserPass.GetResource<dynamic>(soda4x4);
var tokenUserPassRows = tokenUserPassResource.GetRows(10);
Console.WriteLine("Got {0} rows using token, user, pass", tokenUserPassRows.Count());

var keyId = "key-id";
var keySecret = "key-secret";
var clientTokenKeys = new SodaClient(sodaHost, sodaAppToken, keyId, keySecret);
var tokenKeysResource = clientTokenKeys.GetResource<dynamic>(soda4x4);
var tokenKeysRows = tokenKeysResource.GetRows(10);
Console.WriteLine("Got {0} rows using token, keyid, keysecret", tokenKeysRows.Count());
```

**Comment by RealWorldDevelopers** [comment]
Here is an image of using your example code verbatim (except app-token)

```
var sodaHost = "https://data.smgov.net";
var soda4x4 = "w8ue-6cnd";
var clientTokenOnly = new SodaClient(sodaHost, sodaAppToken);
var tokenResource = clientTokenOnly.GetResource<dynamic>(soda4x4);
var tokenRows = tokenResource.GetRows(10);
```

![Capture](https://user-images.githubusercontent.com/18383118/65470155-041c2900-de38-11e9-92f6-a1cd34207181.PNG)

**Comment by RealWorldDevelopers** [comment]
@thekaveman,  I am so embarrassed…   once I wrote I used your code verbatim except token, I realized, that the token may be the issue.  And yes it was.  I was passing the secret and not the key from the app-token.  Once I passed the key and omitted the secret, all versions of my code works as it should.

My deepest apologies on the false report.  Please delete this thread and disregard.

Sincerely
Jim

**Comment by thekaveman** [comment]
All good @RealWorldDevelopers! As long as you got it working, that's all that matters!
